# Generated by Django 5.0.6 on 2024-09-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='CruiseCabinPrice',
            new_name='cruise_cabin_price',
        ),
    ]
