# Generated by Django 5.0.6 on 2024-08-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_quote_number_of_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepassenger',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quotepassenger',
            name='updated_at',
        ),
    ]
