# Generated by Django 5.0.6 on 2024-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_remove_quotepassenger_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='number_of_passengers',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
