# Generated by Django 5.0.6 on 2024-09-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisecabinprice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruises.cruisesession'),
        ),
    ]
