# Generated by Django 5.0.6 on 2024-07-21 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='destination_company_logos/')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Destination Companies',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='cruises.destinationcompany')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
