# Generated by Django 5.0.6 on 2024-10-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruisecabinprice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cruisecabinprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cruisecabinprice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabin_prices', to='cruises.cruisesession'),
        ),
    ]
