# Generated by Django 5.0.6 on 2024-09-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabintype',
            name='amenities',
        ),
        migrations.CreateModel(
            name='CabinTypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cabin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.cabintype')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.equipment')),
            ],
            options={
                'unique_together': {('cabin_type', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='cabintype',
            name='equipment',
            field=models.ManyToManyField(through='cruises.CabinTypeEquipment', to='cruises.equipment'),
        ),
    ]
