# Generated by Django 5.0.6 on 2024-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0004_remove_booking_cruise_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cruisecategory',
            name='equipment',
            field=models.ManyToManyField(related_name='cruise_categories', to='cruises.equipment'),
        ),
    ]
