# Generated by Django 5.0.6 on 2024-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0005_equipment_cruisecategory_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='flyer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cruise_flyers/'),
        ),
    ]
