# Generated by Django 5.0.6 on 2024-09-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='quote.quote'),
        ),
    ]
