# Generated by Django 5.0.6 on 2024-11-19 20:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_passengers', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Booking')], default='draft', max_length=20)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='moderate', max_length=20)),
                ('expiration_date', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('applied_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='cruises.promotion')),
                ('cabin_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='cruises.cabincategory')),
                ('cruise_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='cruises.cruisesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('transfer', 'Transfer'), ('excursion', 'Excursion'), ('insurance', 'Insurance'), ('beverage', 'Beverage Package'), ('dining', 'Dining Package'), ('other', 'Other')], default='other', max_length=20)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='quotes.quote')),
            ],
            options={
                'ordering': ['quote', 'service_type', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='QuotePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Passport Number')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date')),
                ('dietary_requirements', models.TextField(blank=True, verbose_name='Dietary Requirements')),
                ('medical_requirements', models.TextField(blank=True, verbose_name='Medical Requirements')),
                ('is_lead_passenger', models.BooleanField(default=False, help_text='Designate this passenger as the lead contact for the quote', verbose_name='Lead Passenger')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Quote Passenger',
                'verbose_name_plural': 'Quote Passengers',
                'ordering': ['-is_lead_passenger', 'last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'expiration_date'], name='quotes_quot_status_dddf12_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'status'], name='quotes_quot_user_id_4defd9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotepassenger',
            index=models.Index(fields=['quote', 'is_lead_passenger'], name='quotes_quot_quote_i_d9f76f_idx'),
        ),
        migrations.AddIndex(
            model_name='quotepassenger',
            index=models.Index(fields=['passport_number'], name='quotes_quot_passpor_4ab111_idx'),
        ),
    ]
